import type { ShiftItem } from '@/lib/validation/types';
import {
    deduplicateShiftItems,
    filterShiftItemsToSave,
    removeExpandedItemIndex,
    serializeShiftItems,
} from '@/app/staff/finance/hooks/shiftItemsHelpers';

function makeItem(overrides: Partial<ShiftItem> = {}): ShiftItem {
    return {
        id: null,
        clientName: '',
        serviceName: '',
        serviceAmount: 0,
        consumablesAmount: 0,
        bookingId: null,
        createdAt: null,
        ...overrides,
    };
}

describe('shiftItemsHelpers', () => {
    test('serializeShiftItems keeps only stable save-relevant fields', () => {
        expect(
            serializeShiftItems([
                makeItem({
                    clientName: 'Alice',
                    serviceAmount: 1000,
                    bookingId: '11111111-1111-1111-1111-111111111111',
                }),
            ]),
        ).toBe(
            JSON.stringify([
                {
                    id: null,
                    clientName: 'Alice',
                    serviceName: '',
                    serviceAmount: 1000,
                    consumablesAmount: 0,
                    bookingId: '11111111-1111-1111-1111-111111111111',
                },
            ]),
        );
    });

    test('filterShiftItemsToSave removes empty autogenerated client placeholders', () => {
        const items = [
            makeItem({ clientName: 'Клиент 1' }),
            makeItem({ clientName: 'Client 2' }),
            makeItem({ clientName: 'Alice' }),
            makeItem({ clientName: 'Клиент 3', serviceAmount: 500 }),
            makeItem({ bookingId: '11111111-1111-1111-1111-111111111111' }),
        ];

        const result = filterShiftItemsToSave(items);

        expect(result).toEqual([items[2], items[3], items[4]]);
    });

    test('deduplicateShiftItems removes unsaved duplicates when matching saved item exists', () => {
        const saved = makeItem({
            id: '22222222-2222-2222-2222-222222222222',
            clientName: 'Alice',
            createdAt: '2026-03-19T10:00:00.000Z',
        });
        const unsavedDuplicate = makeItem({
            clientName: 'Alice',
            createdAt: '2026-03-19T10:00:03.000Z',
        });
        const unsavedUnique = makeItem({
            clientName: 'Bob',
            createdAt: '2026-03-19T10:00:03.000Z',
        });

        expect(deduplicateShiftItems([saved, unsavedDuplicate, unsavedUnique])).toEqual([
            saved,
            unsavedUnique,
        ]);
    });

    test('removeExpandedItemIndex shifts remaining indexes after deletion', () => {
        expect(removeExpandedItemIndex(new Set([0, 2, 4]), 2)).toEqual(new Set([0, 3]));
        expect(removeExpandedItemIndex(new Set([1, 3]), 0)).toEqual(new Set([0, 2]));
    });
});
