import type { ShiftItem } from '../types';

export function serializeShiftItems(items: ShiftItem[]): string {
    return JSON.stringify(
        items.map((it) => ({
            id: it.id,
            clientName: it.clientName,
            serviceName: it.serviceName,
            serviceAmount: it.serviceAmount,
            consumablesAmount: it.consumablesAmount,
            bookingId: it.bookingId,
        })),
    );
}

export function isMeaningfulShiftItem(item: ShiftItem): boolean {
    if (item.id) return true;
    if (item.bookingId) return true;
    if ((item.serviceAmount ?? 0) > 0 || (item.consumablesAmount ?? 0) > 0) return true;

    if (item.clientName && item.clientName.trim() !== '') {
        const trimmedName = item.clientName.trim();
        const autoGeneratedPattern = /^(Клиент|Client)\s*\d+$/i;

        if (!autoGeneratedPattern.test(trimmedName)) {
            return true;
        }

        if (
            (item.serviceName && item.serviceName.trim() !== '') ||
            (item.serviceAmount ?? 0) > 0 ||
            (item.consumablesAmount ?? 0) > 0
        ) {
            return true;
        }
    }

    return false;
}

export function filterShiftItemsToSave(items: ShiftItem[]): ShiftItem[] {
    return items.filter(isMeaningfulShiftItem);
}

export function deduplicateShiftItems(items: ShiftItem[]): ShiftItem[] {
    return items.filter((item, _index, arr) => {
        if (item.id) {
            return true;
        }

        const hasDuplicateWithId = arr.some((otherItem) => {
            if (!otherItem.id) return false;
            if (otherItem.clientName !== item.clientName) return false;
            if (item.createdAt && otherItem.createdAt) {
                const itemTime = new Date(item.createdAt).getTime();
                const otherTime = new Date(otherItem.createdAt).getTime();
                return Math.abs(itemTime - otherTime) < 5000;
            }
            return false;
        });

        return !hasDuplicateWithId;
    });
}

export function removeExpandedItemIndex(expandedItems: Set<number>, idx: number): Set<number> {
    const updated = new Set<number>();
    expandedItems.forEach((i) => {
        if (i < idx) {
            updated.add(i);
        } else if (i > idx) {
            updated.add(i - 1);
        }
    });
    return updated;
}
